-- paytrackingapp — initial schema
--
-- Conventions, applied without exception below:
--   * money      -> integer cents.        Never numeric, never float.
--   * durations  -> integer minutes.
--   * instants   -> timestamptz (stored UTC, displayed Europe/Dublin).
--   * every table holding user data carries user_id, has RLS enabled AND
--     forced, and has policies for all four verbs.
--
-- Forward-only. Do not edit this file after it has been applied; add a new
-- migration instead.

create extension if not exists pgcrypto;   -- gen_random_uuid()
create extension if not exists btree_gist; -- non-overlapping pay periods


-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

create type public.pay_period_length as enum ('weekly', 'fortnightly', 'monthly');

-- 'manual' is the only value in v1. Calendar or rota import, if it ever
-- happens, adds a value here and nothing else in the app has to care.
create type public.shift_source as enum ('manual');

-- NULL is a meaningful value on settings.sunday_premium_kind and is NOT the
-- same as 'none'. See the comment on that column.
create type public.sunday_premium_kind as enum ('none', 'per_hour', 'multiplier');


-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------------
-- settings — exactly one row per user, written at first run
-- ---------------------------------------------------------------------------

create table public.settings (
  id                            uuid primary key default gen_random_uuid(),
  user_id                       uuid not null unique
                                  references auth.users (id) on delete cascade,

  -- First run, question 1.
  hourly_rate_cents             integer not null check (hourly_rate_cents > 0),

  -- First run, question 2. Irish law gives no right to paid breaks, so this
  -- is a matter of contract and cannot be inferred — it has to be asked.
  breaks_paid                   boolean not null,

  -- First run, question 3.
  pay_period_length             public.pay_period_length not null,

  -- The day the first pay period starts. Derived from the setup date rather
  -- than asked — four questions is already pushing the "faster than Notes"
  -- bar. Every subsequent period is generated from this.
  period_anchor_date            date not null,

  -- First run, question 4.
  --
  -- NULL means "not sure" and is deliberately distinct from 'none'.
  -- There is no statutory Sunday multiplier in Ireland; s.14 OWTA 1997
  -- entitles a Sunday worker to compensation UNLESS Sunday was already
  -- taken into account when the rate was set, which many hospitality
  -- contracts do. So the app cannot derive this — it can only record what
  -- the contract gives.
  --
  -- The NULL/'none' distinction is what lets the app later say "you work
  -- Sundays and no premium appears anywhere — s.14 may entitle you to one".
  -- Collapse the two and that flag can never fire.
  -- See docs/PAY-RULES.md, section: Sunday work.
  sunday_premium_kind           public.sunday_premium_kind,
  sunday_premium_cents_per_hour integer check (sunday_premium_cents_per_hour > 0),
  sunday_premium_basis_points   integer check (sunday_premium_basis_points >= 10000),

  -- Used to prefill the break field on a new shift where breaks are unpaid.
  -- Not asked at first run; it is a default, not a question.
  default_break_minutes         integer not null default 30
                                  check (default_break_minutes between 0 and 480),

  created_at                    timestamptz not null default now(),
  updated_at                    timestamptz not null default now(),

  -- Exactly one premium column may be populated, and only the one that
  -- matches the kind. Enforced here so no code path can produce a settings
  -- row that the pay calculation would have to guess about.
  constraint sunday_premium_coherent check (
    case sunday_premium_kind
      when 'per_hour'   then sunday_premium_cents_per_hour is not null
                         and sunday_premium_basis_points is null
      when 'multiplier' then sunday_premium_basis_points is not null
                         and sunday_premium_cents_per_hour is null
      else                   sunday_premium_cents_per_hour is null
                         and sunday_premium_basis_points is null
    end
  )
);

comment on column public.settings.sunday_premium_basis_points is
  'Integer basis points; 10000 = 1.0x. Integer so no multiplier is ever a float.';

create trigger settings_set_updated_at
  before update on public.settings
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- pay_period
--
-- Periods exist as rows so that actual_paid_cents has somewhere to live.
-- Totals are NEVER stored here — every figure the app shows is derived from
-- the shifts whose work_date falls in the range. A stored total cannot be
-- decomposed later; a derived one always can.
--
-- Note there is deliberately no shift -> pay_period foreign key. Membership
-- is computed from work_date, so changing pay_period_length re-buckets the
-- history instead of orphaning it.
-- ---------------------------------------------------------------------------

create table public.pay_period (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users (id) on delete cascade,

  starts_on         date not null,
  ends_on           date not null,

  -- The watchdog field. Nothing in v1 writes or reads it. It exists from the
  -- first migration because it cannot be backfilled — a period that has come
  -- and gone with nowhere to record what actually landed is a period the app
  -- can never check.
  actual_paid_cents integer check (actual_paid_cents >= 0),

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint pay_period_range_valid check (ends_on >= starts_on),
  constraint pay_period_unique_start unique (user_id, starts_on),

  -- Two overlapping periods would double-count shifts. Structurally impossible.
  constraint pay_period_no_overlap exclude using gist (
    user_id with =,
    daterange(starts_on, ends_on, '[]') with &&
  )
);

create trigger pay_period_set_updated_at
  before update on public.pay_period
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- shift
--
-- Stores planned AND actual for both the finish time and the break, because
-- that gap is the entire point of the app: payroll assumes the shift ended at
-- close and the break was taken; reality often differed and nobody wrote it
-- down.
--
-- Times are instants, not local clock times. Elapsed time between two
-- timestamptz values is correct across the October DST boundary without any
-- special-casing — a night shift on the change is nine hours paid, and it
-- falls out of the subtraction rather than being patched in afterwards.
--
-- work_date is kept separately because a shift that starts 18:00 Saturday and
-- ends 01:20 Sunday belongs to Saturday, for display and for Sunday-premium
-- purposes alike. It is a Europe/Dublin calendar day, not a UTC one.
-- ---------------------------------------------------------------------------

create table public.shift (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references auth.users (id) on delete cascade,

  work_date             date not null,

  planned_start_at      timestamptz not null,
  planned_end_at        timestamptz not null,

  -- NULL until the end-of-week confirmation. NULL is what makes the period
  -- total an estimate, and the UI must show it as one.
  actual_end_at         timestamptz,

  planned_break_minutes integer not null default 0
                          check (planned_break_minutes between 0 and 480),
  actual_break_minutes  integer check (actual_break_minutes between 0 and 480),

  -- Set when the user confirms the actuals for this shift. Separate from
  -- actual_end_at because where breaks are paid the break is never asked, so
  -- "confirmed" cannot be inferred from the two actual_* columns being full.
  -- It is also the contemporaneity stamp: it records WHEN the log was made,
  -- which is what gives the log its evidential weight.
  actuals_confirmed_at  timestamptz,

  source                public.shift_source not null default 'manual',

  -- Unused in v1: the rate comes from settings. Present so that a per-shift
  -- override, or snapshotting the rate in force on the day, is additive
  -- rather than a schema change. NULL means "use the settings rate".
  hourly_rate_cents     integer check (hourly_rate_cents > 0),

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint shift_planned_end_after_start check (planned_end_at > planned_start_at),
  constraint shift_actual_end_after_start  check (actual_end_at is null
                                                  or actual_end_at > planned_start_at)
);

create index shift_user_work_date_idx on public.shift (user_id, work_date desc);

-- Finds the shifts still awaiting confirmation, which is the first half of
-- the weekly ritual.
create index shift_unconfirmed_idx on public.shift (user_id, work_date)
  where actuals_confirmed_at is null;

create trigger shift_set_updated_at
  before update on public.shift
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- Row-level security
--
-- Every row here is someone's personal pay data. FORCE is set as well as
-- ENABLE so that the table owner is subject to the policies too.
--
-- auth.uid() is wrapped in a subselect so the planner evaluates it once per
-- statement rather than once per row.
-- ---------------------------------------------------------------------------

alter table public.settings   enable row level security;
alter table public.settings   force  row level security;
alter table public.pay_period enable row level security;
alter table public.pay_period force  row level security;
alter table public.shift      enable row level security;
alter table public.shift      force  row level security;

-- settings
create policy "settings: owner can read"
  on public.settings for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "settings: owner can insert"
  on public.settings for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "settings: owner can update"
  on public.settings for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "settings: owner can delete"
  on public.settings for delete to authenticated
  using ((select auth.uid()) = user_id);

-- pay_period
create policy "pay_period: owner can read"
  on public.pay_period for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "pay_period: owner can insert"
  on public.pay_period for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "pay_period: owner can update"
  on public.pay_period for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "pay_period: owner can delete"
  on public.pay_period for delete to authenticated
  using ((select auth.uid()) = user_id);

-- shift
create policy "shift: owner can read"
  on public.shift for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "shift: owner can insert"
  on public.shift for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "shift: owner can update"
  on public.shift for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "shift: owner can delete"
  on public.shift for delete to authenticated
  using ((select auth.uid()) = user_id);

-- The anon role is the pre-session role. An anonymous *session* authenticates
-- as `authenticated`, so nothing in this app should ever reach a table as
-- `anon`. Revoke rather than rely on the policies being exhaustive.
revoke all on public.settings, public.pay_period, public.shift from anon;
