-- paytrackingapp — v3: cost breakdown, budget, and AI memory
--
-- Same conventions as the two migrations before it, without exception:
--   * money      -> integer cents. Signed where money can go both ways.
--   * durations  -> integer minutes.
--   * instants   -> timestamptz (stored UTC, displayed Europe/Dublin).
--   * dates      -> Dublin calendar days.
--   * every table holding user data carries user_id, has RLS enabled AND
--     forced, and has policies for all four verbs, with auth.uid() in a
--     subselect so the planner evaluates it once per statement.
--
-- Forward-only. Do not edit this file after it has been applied.
--
-- NOTE ON CLEAN SLATE: v3 replaces anonymous sessions with Google sign-in,
-- and the decision of 2026-09-21 is that no existing data is worth keeping.
-- This migration deliberately does NOT delete those rows. A migration that
-- silently destroys data is the wrong place for that judgement, and RLS
-- already makes the orphaned anonymous rows invisible to the new account.
-- To actually clear them, run this separately and deliberately:
--
--   delete from auth.users where is_anonymous;   -- cascades to every table
--
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

-- How much a goal line can be trusted. The target is a sum of these, so the
-- sum's own reliability is only as good as its weakest line — which is why
-- the confidence travels with the amount rather than sitting on the goal.
create type public.line_confidence as enum ('quoted', 'researched', 'guess');

create type public.outgoing_cadence as enum ('weekly', 'fortnightly', 'monthly', 'yearly');

create type public.txn_source as enum ('manual', 'revolut_csv');

-- Who decided a transaction's category. The model is allowed to guess; the
-- user is allowed to overrule it, and the app has to be able to tell which
-- is which before it trusts a spending total.
create type public.categorised_by as enum ('user', 'model');

-- Who asserted a profile fact. Same reasoning.
create type public.fact_source as enum ('user', 'model');

-- The Messages API has two roles. Tool results come back as user-role
-- content blocks, not a third role, so there is no 'tool' value here.
create type public.ai_role as enum ('user', 'assistant');

-- A CLOSED vocabulary, deliberately. The model targets these and nothing
-- else; an open text field would let it invent a new category every week and
-- make spending-by-category meaningless.
--
-- 'transfer' matters more than it looks: moving money into savings is not
-- spending, and counting it as such would make every good month look like a
-- bad one. 'income' is the same idea in reverse — wages landing are not a
-- negative expense.
create type public.spend_category as enum (
  'groceries',
  'eating_out',
  'transport',
  'rent',
  'bills',
  'health',
  'education',
  'shopping',
  'entertainment',
  'travel',
  'fees',
  'income',
  'transfer',
  'other'
);


-- ---------------------------------------------------------------------------
-- goal_line — the breakdown behind the target
--
-- The target stops being a number somebody typed and becomes the sum of what
-- the trip actually costs, line by line, each carrying how much it can be
-- trusted. It improves as real numbers arrive: a 'guess' at flights becomes
-- 'researched' with a citation, then 'quoted' when the booking exists.
-- ---------------------------------------------------------------------------

create table public.goal_line (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users (id) on delete cascade,
  goal_id            uuid not null references public.goal (id) on delete cascade,

  label              text not null check (char_length(label) between 1 and 80),
  amount_cents       integer not null check (amount_cents > 0),
  confidence         public.line_confidence not null default 'guess',

  -- Where the figure came from, and when that was true. Same discipline as
  -- docs/PAY-RULES.md: a number without a date attached is a number nobody
  -- can re-check.
  source_url         text check (source_url is null or char_length(source_url) <= 2048),
  source_checked_on  date,

  sort_order         integer not null default 0,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  -- A 'researched' line is a claim about the outside world, so it must carry
  -- its citation. Enforced here rather than in the AI prompt, because a
  -- prompt is a request and a constraint is a guarantee.
  constraint goal_line_researched_is_sourced check (
    confidence <> 'researched'
    or (source_url is not null and source_checked_on is not null)
  )
);

create index goal_line_goal_idx on public.goal_line (goal_id, sort_order, created_at);

create trigger goal_line_set_updated_at
  before update on public.goal_line
  for each row execute function public.set_updated_at();

comment on table public.goal_line is
  'The target is the SUM of these lines. See goal.target_cents for the interim rule.';


-- ---------------------------------------------------------------------------
-- goal.target_cents becomes optional
--
-- The target is now the sum of goal_line. The column is kept, and kept
-- writable, only so the app keeps working between this migration and the
-- screens that read the lines — retiring a column in the same step that
-- stops writing it is how you get an outage.
--
-- Rule while both exist: if the goal has lines, the target is their sum and
-- this column is ignored. It is dropped in a later migration once nothing
-- reads it.
-- ---------------------------------------------------------------------------

alter table public.goal alter column target_cents drop not null;

comment on column public.goal.target_cents is
  'Superseded by sum(goal_line.amount_cents). Kept temporarily; ignored when lines exist.';


-- ---------------------------------------------------------------------------
-- outgoing — recurring money out
--
-- The backbone of the Budget tab. Transactions say what happened; outgoings
-- say what is committed to happen again, which is the half you need to
-- project a savings rate forward.
-- ---------------------------------------------------------------------------

create table public.outgoing (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users (id) on delete cascade,

  label         text not null check (char_length(label) between 1 and 80),
  amount_cents  integer not null check (amount_cents > 0),
  cadence       public.outgoing_cadence not null,
  category      public.spend_category not null default 'other',

  started_on    date not null,

  -- Ending an outgoing sets this; it never deletes the row. Rent that ran
  -- from January to June is a true fact about January to June, and a budget
  -- that forgets it cannot explain where the money went.
  ended_on      date,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint outgoing_dates_valid check (ended_on is null or ended_on >= started_on)
);

create index outgoing_user_active_idx on public.outgoing (user_id, started_on desc)
  where ended_on is null;

create trigger outgoing_set_updated_at
  before update on public.outgoing
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- txn — transactions
--
-- Signed, exactly like contribution: money out is negative, money in is
-- positive, and a total is a plain sum. Two tables with opposite sign
-- conventions would guarantee a sign error eventually.
-- ---------------------------------------------------------------------------

create table public.txn (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users (id) on delete cascade,

  posted_on       date not null,
  description     text not null check (char_length(description) between 1 and 300),
  amount_cents    integer not null check (amount_cents <> 0),

  category        public.spend_category not null default 'other',
  categorised_by  public.categorised_by not null default 'user',

  source          public.txn_source not null default 'manual',

  -- The importer's idempotency key, same shape as contribution.external_id.
  -- Null for anything hand-entered.
  external_id     text check (external_id is null or char_length(external_id) <= 200),

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index txn_user_date_idx on public.txn (user_id, posted_on desc);
create index txn_user_category_idx on public.txn (user_id, category, posted_on desc);

-- Re-importing the same statement must not double-count it. This is the
-- whole reason CSV import is safe to run twice.
create unique index txn_external_once
  on public.txn (user_id, source, external_id)
  where external_id is not null;

create trigger txn_set_updated_at
  before update on public.txn
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- profile_fact — durable memory
--
-- "Remembers me" means rows the rest of the app can compute with, not a
-- transcript nobody can query. Destination, departure month, rent, the
-- buffer the user will not dip below.
-- ---------------------------------------------------------------------------

create table public.profile_fact (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users (id) on delete cascade,

  key           text not null check (char_length(key) between 1 and 60),
  value         text not null check (char_length(value) between 1 and 500),

  learned_on    date not null default (now() at time zone 'Europe/Dublin')::date,

  -- Null means the model asserted it and the user has not agreed yet. Those
  -- show as unconfirmed in the UI and can be deleted.
  confirmed_at  timestamptz,
  source        public.fact_source not null,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- One value per key: this is memory, not a log.
  constraint profile_fact_one_per_key unique (user_id, key),

  -- Anything the user said is confirmed by definition. Only the model can
  -- leave something pending.
  constraint profile_fact_user_facts_are_confirmed check (
    source = 'model' or confirmed_at is not null
  )
);

create trigger profile_fact_set_updated_at
  before update on public.profile_fact
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- conversation / ai_message — the log
--
-- Stored because it is useful to scroll back, and because a proposal card
-- re-renders from the tool result already sitting in ai_message.content.
-- That is why there is no proposal table: a proposal is not state, it is a
-- message that has been read.
-- ---------------------------------------------------------------------------

create table public.conversation (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,

  title       text check (title is null or char_length(title) <= 120),

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index conversation_user_recent_idx on public.conversation (user_id, updated_at desc);

create trigger conversation_set_updated_at
  before update on public.conversation
  for each row execute function public.set_updated_at();

create table public.ai_message (
  id               uuid primary key default gen_random_uuid(),
  -- Carried here as well as on conversation, so the RLS policy is a column
  -- comparison rather than a join on every row read.
  user_id          uuid not null references auth.users (id) on delete cascade,
  conversation_id  uuid not null references public.conversation (id) on delete cascade,

  role             public.ai_role not null,

  -- The FULL content blocks, not just the text. Tool uses, tool results,
  -- thinking blocks and citations all live here; flattening to a string
  -- would throw away the proposals the cards are rendered from and the
  -- citations the goal lines depend on.
  content          jsonb not null,

  created_at       timestamptz not null default now()
);

create index ai_message_thread_idx on public.ai_message (conversation_id, created_at);


-- ---------------------------------------------------------------------------
-- Row-level security
--
-- Every row here is personal financial data, and two of these tables now
-- hold things a model wrote. ENABLE and FORCE on all of them, policies for
-- all four verbs, no exceptions.
-- ---------------------------------------------------------------------------

alter table public.goal_line    enable row level security;
alter table public.goal_line    force  row level security;
alter table public.outgoing     enable row level security;
alter table public.outgoing     force  row level security;
alter table public.txn          enable row level security;
alter table public.txn          force  row level security;
alter table public.profile_fact enable row level security;
alter table public.profile_fact force  row level security;
alter table public.conversation enable row level security;
alter table public.conversation force  row level security;
alter table public.ai_message   enable row level security;
alter table public.ai_message   force  row level security;

-- goal_line
create policy "goal_line: owner can read"
  on public.goal_line for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "goal_line: owner can insert"
  on public.goal_line for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "goal_line: owner can update"
  on public.goal_line for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "goal_line: owner can delete"
  on public.goal_line for delete to authenticated
  using ((select auth.uid()) = user_id);

-- outgoing
create policy "outgoing: owner can read"
  on public.outgoing for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "outgoing: owner can insert"
  on public.outgoing for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "outgoing: owner can update"
  on public.outgoing for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "outgoing: owner can delete"
  on public.outgoing for delete to authenticated
  using ((select auth.uid()) = user_id);

-- txn
create policy "txn: owner can read"
  on public.txn for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "txn: owner can insert"
  on public.txn for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "txn: owner can update"
  on public.txn for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "txn: owner can delete"
  on public.txn for delete to authenticated
  using ((select auth.uid()) = user_id);

-- profile_fact
create policy "profile_fact: owner can read"
  on public.profile_fact for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "profile_fact: owner can insert"
  on public.profile_fact for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "profile_fact: owner can update"
  on public.profile_fact for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "profile_fact: owner can delete"
  on public.profile_fact for delete to authenticated
  using ((select auth.uid()) = user_id);

-- conversation
create policy "conversation: owner can read"
  on public.conversation for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "conversation: owner can insert"
  on public.conversation for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "conversation: owner can update"
  on public.conversation for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "conversation: owner can delete"
  on public.conversation for delete to authenticated
  using ((select auth.uid()) = user_id);

-- ai_message
create policy "ai_message: owner can read"
  on public.ai_message for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "ai_message: owner can insert"
  on public.ai_message for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "ai_message: owner can update"
  on public.ai_message for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "ai_message: owner can delete"
  on public.ai_message for delete to authenticated
  using ((select auth.uid()) = user_id);

revoke all on
  public.goal_line,
  public.outgoing,
  public.txn,
  public.profile_fact,
  public.conversation,
  public.ai_message
from anon;
